
name: Auto Renew MWS

on:
  schedule: 
    - cron: '30 20 */6 * *' # 每6天UTC 22:30 (北京时间6点半, 一般都会推迟8点之后运行),可自行调整
  workflow_dispatch:

jobs:
  Renew-mws:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: ⚙ 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: 🛠️ 安装系统依赖和 Python 依赖
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq wget
          pip install curl_cffi

      - name: ⚙ 设置代理 (sing-box)
        continue-on-error: true
        env:
          NODE_LINK: ${{ secrets.NODE_LINK }}
        run: |
          bash <(wget -qO- https://main.ssss.nyc.mn/setup_proxy.sh)

      - name: 🚀 运行续期脚本
        env:
          EMAIL: ${{ secrets.EMAIL }}
          COOKIE: ${{ secrets.COOKIE }}
          SERVER_IDS: ${{ secrets.SERVER_IDS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          PYTHONUNBUFFERED: "1"
        run: |
          python3 app.py

      - name: 🧽 清理进程和临时文件
        if: always()
        run: |
          pkill -f sing-box || true
          rm -f sing-box sing-box-config.json sing-box.log

      # 更新时间到time.txt,避免6个月未更新导致工作流暂停
      - name: 🕒 提交运行时间
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" > time.txt
          git add time.txt
          if git diff --cached --quiet; then
            echo "No need to commit"
          else
            git commit -m "⏱️ Auto Update by Github Actions $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
          
      - name: 🧹 清理旧的工作流运行记录
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          runs=$(gh run list --workflow="${{ github.workflow }}" --limit=100 --json databaseId --jq '.[].databaseId')
          count=0
          for run_id in $runs; do
            count=$((count + 1))
            if [ $count -gt 1 ]; then
              echo "删除运行记录: $run_id"
              gh run delete $run_id || true
            fi
          done
